apiVersion: v1        # version de l'API Kubernetes pour les Secrets
kind: Secret        
metadata:
  name: crypto-secret 
type: Opaque          # type générique pour les secrets custom
data:  
  DB_USER: Y3J5cHRvdXNlcg==   
  DB_PASSWORD: Y3J5cHRvMTIz   