apiVersion: v1        # version de l'API Kubernetes pour les Secrets
kind: Secret          # type d'objet = Secret
metadata:
  name: crypto-secret # nom du Secret — les autres fichiers YAML y feront référence
type: Opaque          # type générique pour les secrets custom
data:
  DB_HOST: bG9jYWxob3N0        
  DB_NAME: Y3J5cHRvcHVsc2U=   
  DB_USER: Y3J5cHRvdXNlcg==   
  DB_PASSWORD: Y3J5cHRvMTIz   