apiVersion: v1
kind: Secret
metadata:
  name: crypto-secret
  namespace: cryptopulse
type: Opaque
data:
  POSTGRES_USER: Y3J5cHRvdXNlcg==      # cryptouser encodé en base64
  POSTGRES_PASSWORD: Y3J5cHRvMTIz      # crypto123 encodé en base64